name: Automated Wine update
on:
  schedule:
    - cron:  '0 12 * * Sat'
  workflow_dispatch:

jobs:
  updateWine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.PAT }}
      - name: follow for-next
        run: |
          git fetch origin for-next
          git merge --ff-only origin/for-next
      - name: Get Latest Wine Version
        id: wine
        run: |
          echo LATEST_TAG=$(curl -sL https://hub.docker.com/v2/namespaces/panard/repositories/wine/tags | jq -r '.results[].name' | grep '\-wow64$' | head -n1) >> $GITHUB_ENV
          echo CURRENT_TAG=$(grep FROM Dockerfile|cut -d: -f2) >> $GITHUB_ENV
      - name: Update Wine
        if: env.CURRENT_TAG != env.LATEST_TAG
        run: |
            sed -i "s:FROM .*$:FROM panard/wine:$LATEST_TAG" docker-wine/Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update wine to ${{ steps.wine.outputs.release_tag }}
          title: Update wine to ${{ steps.wine.outputs.release_tag }}
          body: |
              Updates wine to ${{ steps.wine.outputs.release_tag }}

              ```
              ./run-mtgo --update --test panard/mtgo:pr<#ID>
              ```
          assignees: pauleve
          labels: autodocker
          branch: auto/wine-updates
